### ISSUE TITLE
how to set cloudinary envs ?

### ISSUE THREAD

**Issue by bloblink** [rbonweb/ghost-v3-on-heroku#1]
Hi Rohit ,
how to set cloudinary envs ?
waiting for your response
finest regards

**Comment by rbonweb** [comment]
@bloblink 
Thanks for looking into the repo.

Currently, I am working on an upgrade to the Cloudinary.
Right now it has only support of SMTP and  SQL database.
Files uploads are set to local.

Rohit Bhadani

**Comment by bloblink** [comment]
Hello Again Rohit ,
so interesting to see changes about support cloudinary,
waiting for your repo commit changelog,
finest regards

**Comment by rbonweb** [comment]
Hello @bloblink 
I have added Cloudinary for the file storage and also on one-click button installer I have added a field to add to set CLOUDINARY_URL 
Thank you.
